spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/onework-test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
  sql:
    init:
      schema-locations: classpath:db/schema-onework.sql
      data-locations: classpath:db/data-onework.sql
      mode: always
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted_at
      logic-not-delete-value: "null"
      logic-delete-value: now()
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
  servlet:
    context-path: /api
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true